#!/usr/bin/env bash

#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=1G
#SBATCH --time=00:05:00
#SBATCH --partition=pibu_el8
#SBATCH --job-name=RNAseq_dir_set_up
#SBATCH --output=/data/users/aschmid/RNAseq_project/RNAseq_breastcancer/output/dir_set_up_output_%j.o
#SBATCH --error=/data/users/aschmid/RNAseq_project/RNAseq_breastcancer/output/dir_set_up_error_%j.o

WORKING_DIR="/data/users/aschmid/RNAseq_project/RNAseq_breastcancer"
TOOLS_DIR="/data/courses/rnaseq_course/tools"
READS_DIR="/data/courses/rnaseq_course/breastcancer_de/reads"

# Creating a directory for the outpout files of the worklfow
mkdir "$WORKING_DIR/output"

# Generating a file that will contain a list of path to the fastq files
$TOOLS_DIR/get_samplelist.sh $READS_DIR > $WORKING_DIR/reads_list.tsv